apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cowweb-v1.1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cowweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cowweb
        version: v1.1
    spec:
      containers:
      - name: cowweb
        image: iad.ocir.io/hhiroshell1/cowweb:demo-v1.1
        ports:
        - name: api
          containerPort: 8080
        env:
        - name: REDIS_PORT_6379_TCP_ADDR
          value: "redis"
        - name: REDIS_PORT_6379_TCP_PORT
          value: "6379"
        readinessProbe:
          httpGet:
            path: /cowsay/api/ping
            port: ap
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /cowsay/api/ping
            port: api
          initialDelaySeconds: 15
          periodSeconds: 20
        imagePullPolicy: Always
      imagePullSecrets:
        - name: cowweb-secret
