apiVersion: v1
kind: Service
metadata:
  name: cowweb
spec:
  type: NodePort
  ports:
  - name: api
    port: 8080
    nodePort: 30080
  - name: debug
    port: 8081
    nodePort: 30081
  selector:
    app: cowweb
    profile: local_dev
---
apiVersion: v1
kind: Pod
metadata:
  name: cowweb
  labels:
    app: cowweb
    profile: local_dev
spec:
  containers:
  - name: cowweb
    image: docker.io/hhayakaw/cowweb
