apiVersion: v1
kind: Service
metadata:
  name: cowweb
spec:
  type: NodePort
  selector:
    app: cowweb
    profile: release
  ports:
  - name: api
    port: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: cowweb
  labels:
    app: cowweb
    profile: release
spec:
  containers:
  - name: cowweb
    image: docker.io/hhayakaw/cowweb
    ports:
    - name: api
      containerPort: 8080
    readinessProbe:
      httpGet:
        path: /cowsay/ping
        port: api
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /cowsay/ping
        port: api
      initialDelaySeconds: 15
      periodSeconds: 20
